name: ci

on:
  push:
    branches: [ master ]

jobs:
  gcr:
    runs-on: ubuntu-18.04

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |-
          docker build --build-arg -t eu.gcr.io/l15-testnet/eth2stats-dashboard:latest .

      - name: Authorize GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate docker and push image to GCR
        run: |-
          gcloud auth configure-docker -q
          docker push eu.gcr.io/l15-testnet/eth2stats-dashboard:latest